sudo: required
env:
- distro: centos7
  init: "/usr/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: centos6
  init: "/sbin/init"
  run_opts: ''
- distro: fedora24
  init: "/usr/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: ubuntu1604
  init: "/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: ubuntu1404
  init: "/sbin/init"
  run_opts: ''
- distro: debian8
  init: "/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
services:
- docker
before_install:
- docker pull geerlingguy/docker-${distro}-ansible:latest
script:
- container_id=$(mktemp)
- docker run --detach --volume="${PWD}":/etc/ansible/roles/test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest
  "${init}" > "${container_id}"
- 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/test/tests/test.yml
  --syntax-check # Run the role/playbook with ansible-playbook.

'
- 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/test/tests/test.yml

'
- idempotence=$(mktemp)
- 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/test/tests/test.yml
  | tee -a ${idempotence}

'
- 'tail ${idempotence} | grep -q ''changed=0.*failed=0'' && (echo ''Idempotence test:
  pass'' && exit 0) || (echo ''Idempotence test: fail'' && exit 1)

'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: G5U3addFhrUKgIpKz9FJqx2AXcVVL+RvmuqlLT7lAk1d1+LdNbFgSYoywlUZ9lv/zbYDBAFgdh9F+tawvcH4MA86l2d/rhdYcYSaCc9Hk7keVkvrmIUsMVNm/JCnUBNcoIpbdAhNCkxXwbqdUP++O52GIHCfJC+eC1XgHIOVOd74we0tFYgkYL0QFsd4F21yx0SMJBGhJoD4fh86YkHlHGUDZaAbZWgGs/mdzVYM9C4P0iKQuuWiwAT9WPMJtB4jRdA/03SAeSZ0RM/Xbw2Vyn2oEKqO2fyH21Qp2OZhiUW2E0kczK3oMcpj/m84hstbCZ62PJWlfoDGKYnbDbRyymlEK1DY02b+JdAyDHRvBy6sYHAY+Eq5BUHQ2b5PuumkOpssCPz6i7O+hS+apZ0gWB1XyRGXejTyzeLaB4+XXxKDbuAlsE2RUPDqZY3H1qGUU+djOkpT5S0TB5g1SbwIfQ20byC4+2oRmagbDTDaHJq822ajXwsoC/9F00c9buaA5u4CZWgNHnLq12rihKV9IyvjNeQdBRvgX0HjUK28XRxshTIp0tsNZ+fScPbVuTHWApNBbPUhB+zMlzw5Hs8uDZVYj+Cv0nSqAFTgRzM+XhEeL4A3WfzX6rJZ+Ego+ExEC6hj1VvaiOSEVKRVfV4+G/qQZOl4A9Uug5GusPI7E8c=
